### ISSUE TITLE
consider breaking apart parser and data packages

### ISSUE THREAD

**Issue by girtsf** [cmsis-svd/cmsis-svd#63]
Hi, thank you for the great package!

One suggestion I have is to consider breaking apart the package into SVD parser and a separate data package. I'm currently using just the parser for a project, but this causes me to pull in 823MB of data that I don't use.

Thank you! :)

**Comment by VincentDary** [comment]
Fixed in [#182](https://github.com/cmsis-svd/cmsis-svd/pull/182)
